version: '2'
services:
    charactercreator-app:
        image: charactercreator
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://charactercreator-postgresql:5432/CharacterCreator
            - JHIPSTER_SLEEP=30 # gives time for the JHipster Registry to boot before the application
        ports:
            - 8080:8080
    charactercreator-postgresql:
        extends:
            file: postgresql.yml
            service: charactercreator-postgresql
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/docker-config/
